### ISSUE TITLE
&MULTIPART_PART_HEADERS supported only in the last version of modsecurity

### ISSUE THREAD

**Issue by codebyoul** [Brets0150/DiamondHardLAMP#2]
AH00526: Syntax error on line 43 of /usr/share/modsecurity-crs/rules/REQUEST-922-MULTIPART-ATTACK.conf:
Error creating rule: Unknown variable: &MULTIPART_PART_HEADERS

**Comment by Brets0150** [comment]
Hi Oulfr,
The modsec rules that DHL uses are pulled directly from the OWASP CRS (Official Repository) on GitHub ("https://github.com/coreruleset/coreruleset.git"). DHL pulls an update from this repo daily. So, the syntax error is within the OWASP repo. 

It looks like this is a known issue; https://github.com/coreruleset/coreruleset/issues/3129

However, it sounds like it only affects Debian? I am on Ubuntu 20.04 LST with DHL and have not had this error. Try manually upgrading the ModSec package.
